using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace SaaS.Engine
{
    #region Generated by Lokad Code DSL
    [DataContract(Namespace = "Frog.Stuff")]
public partial class TaskInfo
    {
        [DataMember(Order = 1)] public TerminalId Id { get; private set; }
        [DataMember(Order = 2)] public string Name { get; private set; }
        [DataMember(Order = 3)] public TaskStatus Status { get; private set; }
        
        TaskInfo () {}
        public TaskInfo (TerminalId id, string name, TaskStatus status)
        {
            Id = id;
            Name = name;
            Status = status;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class PipelineStatus
    {
        [DataMember(Order = 1)] public TaskInfo[] Tasks { get; private set; }
        
        PipelineStatus () 
{
            Tasks = new TaskInfo[0];
        }
        public PipelineStatus (TaskInfo[] tasks)
        {
            Tasks = tasks;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class CheckoutInfo
    {
        [DataMember(Order = 1)] public string Comment { get; private set; }
        [DataMember(Order = 2)] public string Revision { get; private set; }
        
        CheckoutInfo () {}
        public CheckoutInfo (string comment, string revision)
        {
            Comment = comment;
            Revision = revision;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class ProjectCheckedOut : IEvent<BuildId>
    {
        [DataMember(Order = 1)] public BuildId Id { get; private set; }
        [DataMember(Order = 2)] public ProjectId ProjectId { get; private set; }
        [DataMember(Order = 3)] public string RepoUrl { get; private set; }
        [DataMember(Order = 4)] public CheckoutInfo Info { get; private set; }
        
        ProjectCheckedOut () {}
        public ProjectCheckedOut (BuildId id, ProjectId projectId, string repoUrl, CheckoutInfo info)
        {
            Id = id;
            ProjectId = projectId;
            RepoUrl = repoUrl;
            Info = info;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class BuildStarted : IEvent<BuildId>
    {
        [DataMember(Order = 1)] public BuildId Id { get; private set; }
        [DataMember(Order = 2)] public ProjectId ProjectId { get; private set; }
        [DataMember(Order = 3)] public PipelineStatus Status { get; private set; }
        [DataMember(Order = 4)] public AgentId AgentId { get; private set; }
        
        BuildStarted () {}
        public BuildStarted (BuildId id, ProjectId projectId, PipelineStatus status, AgentId agentId)
        {
            Id = id;
            ProjectId = projectId;
            Status = status;
            AgentId = agentId;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class BuildEnded : IEvent<BuildId>
    {
        [DataMember(Order = 1)] public BuildId Id { get; private set; }
        [DataMember(Order = 2)] public ProjectId ProjectId { get; private set; }
        [DataMember(Order = 3)] public BuildTotalEndStatus Status { get; private set; }
        
        BuildEnded () {}
        public BuildEnded (BuildId id, ProjectId projectId, BuildTotalEndStatus status)
        {
            Id = id;
            ProjectId = projectId;
            Status = status;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class BuildUpdated : IEvent<BuildId>
    {
        [DataMember(Order = 1)] public BuildId Id { get; private set; }
        [DataMember(Order = 2)] public ProjectId ProjectId { get; private set; }
        [DataMember(Order = 3)] public int TaskIndex { get; private set; }
        [DataMember(Order = 4)] public TaskStatus TaskStatus { get; private set; }
        
        BuildUpdated () {}
        public BuildUpdated (BuildId id, ProjectId projectId, int taskIndex, TaskStatus taskStatus)
        {
            Id = id;
            ProjectId = projectId;
            TaskIndex = taskIndex;
            TaskStatus = taskStatus;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class TerminalUpdated : IEvent<TerminalId>
    {
        [DataMember(Order = 1)] public TerminalId Id { get; private set; }
        [DataMember(Order = 2)] public BuildId BuildId { get; private set; }
        [DataMember(Order = 3)] public ProjectId ProjectId { get; private set; }
        [DataMember(Order = 4)] public string Content { get; private set; }
        [DataMember(Order = 5)] public int ContentSequnceIndex { get; private set; }
        
        TerminalUpdated () {}
        public TerminalUpdated (TerminalId id, BuildId buildId, ProjectId projectId, string content, int contentSequnceIndex)
        {
            Id = id;
            BuildId = buildId;
            ProjectId = projectId;
            Content = content;
            ContentSequnceIndex = contentSequnceIndex;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class ProjectRegistered : IEvent<ProjectId>
    {
        [DataMember(Order = 1)] public ProjectId Id { get; private set; }
        [DataMember(Order = 2)] public string RepoUrl { get; private set; }
        
        ProjectRegistered () {}
        public ProjectRegistered (ProjectId id, string repoUrl)
        {
            Id = id;
            RepoUrl = repoUrl;
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class AgentJoined : IEvent<AgentId>
    {
        [DataMember(Order = 1)] public AgentId Id { get; private set; }
        [DataMember(Order = 2)] public string[] Capabilities { get; private set; }
        
        AgentJoined () 
{
            Capabilities = new string[0];
        }
        public AgentJoined (AgentId id, string[] capabilities)
        {
            Id = id;
            Capabilities = capabilities;
        }
    }
    
    public interface IAgentState
    {
        void When(AgentJoined e);
    }
    
    public interface IProjectState
    {
        void When(ProjectRegistered e);
    }
    
    public interface ITaskState
    {
        void When(TerminalUpdated e);
    }
    
    public interface IBuildState
    {
        void When(ProjectCheckedOut e);
        void When(BuildStarted e);
        void When(BuildEnded e);
        void When(BuildUpdated e);
    }
    #endregion
}
