using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace SaaS.Engine
{
    #region Generated by Lokad Code DSL
    [DataContract(Namespace = "Frog.Stuff")]
public partial class BuildStarted : IEvent<BuildId>
    {
        [DataMember(Order = 1)] public BuildId Id { get; private set; }
        [DataMember(Order = 2)] public TimeSpan ActivityThreshold { get; private set; }
        
        BuildStarted () {}
        public BuildStarted (BuildId id, TimeSpan activityThreshold)
        {
            Id = id;
            ActivityThreshold = activityThreshold;
        }
        
        public override string ToString()
        {
            return string.Format(@"It is done");
        }
    }
    [DataContract(Namespace = "Frog.Stuff")]
public partial class RegistrationInfo
    {
        [DataMember(Order = 1)] public string ContactEmail { get; private set; }
        [DataMember(Order = 2)] public string CustomerName { get; private set; }
        [DataMember(Order = 3)] public string OptionalUserIdentity { get; private set; }
        [DataMember(Order = 4)] public string OptionalUserPassword { get; private set; }
        [DataMember(Order = 5)] public string OptionalCompanyPhone { get; private set; }
        [DataMember(Order = 6)] public string OptionalCompanyUrl { get; private set; }
        [DataMember(Order = 7)] public string OptionalUserDisplay { get; private set; }
        [DataMember(Order = 8)] public RegistrationHttpHeader[] Headers { get; private set; }
        [DataMember(Order = 9)] public DateTime CreatedUtc { get; private set; }
        
        RegistrationInfo () 
{
            Headers = new RegistrationHttpHeader[0];
        }
        public RegistrationInfo (string contactEmail, string customerName, string optionalUserIdentity, string optionalUserPassword, string optionalCompanyPhone, string optionalCompanyUrl, string optionalUserDisplay, RegistrationHttpHeader[] headers, DateTime createdUtc)
        {
            ContactEmail = contactEmail;
            CustomerName = customerName;
            OptionalUserIdentity = optionalUserIdentity;
            OptionalUserPassword = optionalUserPassword;
            OptionalCompanyPhone = optionalCompanyPhone;
            OptionalCompanyUrl = optionalCompanyUrl;
            OptionalUserDisplay = optionalUserDisplay;
            Headers = headers;
            CreatedUtc = createdUtc;
        }
    }
    
    public interface IBuildState
    {
        void When(BuildStarted e);
    }
    #endregion
}
